export type Topic =
  | "Command & conduct"
  | "Response readiness"
  | "Work rules"
  | "Fire operations"
  | "EMS & HazMat"
  | "Rescue & safety";

export type Question = {
  id: number;
  ruleId: number;
  topic: Topic;
  prompt: string;
  options: string[];
  answer: number;
  explanation: string;
  source: string;
};

type SourceQuestion = Omit<Question, "ruleId">;

const baseQuestions: SourceQuestion[] = [
  {
    id: 1,
    topic: "Command & conduct",
    prompt: "A member wants an interview with someone above their supervisor. What is the normal first step?",
    options: [
      "Contact the Administrative Office directly",
      "Ask the supervisor and briefly state the reason",
      "Send a written request to the Fire Chief",
      "Ask any Chief Officer encountered on duty",
    ],
    answer: 1,
    explanation: "The request normally goes through the member's supervisor, with a brief reason. Certain issues such as harassment or safety are not restricted by this route.",
    source: "Article 3 §3.1.2, p. 1",
  },
  {
    id: 2,
    topic: "Command & conduct",
    prompt: "A superior officer gives an order that conflicts with a previous order. What should the member do?",
    options: [
      "Follow the newest order without comment",
      "Follow the order from the higher-ranking officer",
      "Inform the officer who issued the conflicting order and follow that officer's instructions",
      "Stop work until both officers meet",
    ],
    answer: 2,
    explanation: "The member informs the officer who issued the conflicting order and is then governed by that officer's instructions.",
    source: "Article 3 §3.1.6, p. 2",
  },
  {
    id: 3,
    topic: "Command & conduct",
    prompt: "If a member doubts the legality of an order, the member should:",
    options: [
      "Refuse it immediately",
      "Ask the issuing supervisor to clarify it in writing or confer with higher authority",
      "Complete it and file a grievance afterward",
      "Ask another firefighter for an interpretation",
    ],
    answer: 1,
    explanation: "Members must not obey an order they know or should know requires an illegal act. When in doubt, they should request written clarification or confer with higher authority.",
    source: "Article 3 §3.1.7, p. 2",
  },
  {
    id: 4,
    topic: "Command & conduct",
    prompt: "A member charged with a crime other than a minor traffic offense must report it to the Administrative Office within:",
    options: ["24 hours", "48 hours", "72 hours", "Five business days"],
    answer: 2,
    explanation: "The charge must be reported as soon as possible, not to exceed 72 hours from when the member becomes aware of it.",
    source: "Article 3 §3.2.38(a), p. 8",
  },
  {
    id: 5,
    topic: "Command & conduct",
    prompt: "A current member must notify the Administrative Office of the outcome of a criminal case within:",
    options: ["12 hours", "24 hours", "72 hours", "Seven days"],
    answer: 1,
    explanation: "The outcome must be reported within 24 hours.",
    source: "Article 3 §3.2.38(b), p. 8",
  },
  {
    id: 6,
    topic: "Response readiness",
    prompt: "What is the minimum driver-license requirement while operating Fire Department apparatus?",
    options: [
      "Class C with no endorsement",
      "Commercial Class B only",
      "Valid Class D with an F endorsement, or equivalent",
      "Any valid Tennessee license",
    ],
    answer: 2,
    explanation: "Drivers must possess at least a valid Class D operator's license with an F endorsement, or equivalent, and report any status change.",
    source: "Article 3 §3.4.2, p. 9",
  },
  {
    id: 7,
    topic: "Response readiness",
    prompt: "At minimum, what PPE must firefighting personnel wear while responding to structural fires and fire alarms?",
    options: [
      "Helmet and gloves",
      "Turnout coat and turnout pants",
      "Full PPE including SCBA facepiece",
      "Station uniform and safety vest",
    ],
    answer: 1,
    explanation: "The minimum is turnout coat and turnout pants. Helmets are not to be worn while traveling, and seatbelts may not be unbuckled to don PPE.",
    source: "Article 3 §3.4.4, p. 9",
  },
  {
    id: 8,
    topic: "Response readiness",
    prompt: "If a radio goes out of service during an emergency, which statement is correct?",
    options: [
      "Notify Dispatch after the incident",
      "Notify the Incident Commander; every interior crew member must have a working portable radio",
      "Only the Company Officer needs a working portable radio",
      "The affected member may remain interior if paired with another member",
    ],
    answer: 1,
    explanation: "The IC must be notified, and each member of an interior crew must have a working portable radio.",
    source: "Article 3 §3.4.17, p. 11",
  },
  {
    id: 9,
    topic: "Response readiness",
    prompt: "An officer calling for a second alarm or greater must tell Dispatch:",
    options: ["The estimated property value", "The extent of the fire", "The nearest hydrant color", "The number of off-duty personnel needed"],
    answer: 1,
    explanation: "The officer calling for a second alarm or greater must inform Dispatch of the extent of the fire.",
    source: "Article 3 §3.4.16, p. 11",
  },
  {
    id: 10,
    topic: "Response readiness",
    prompt: "When is hearing protection required?",
    options: [
      "Only during emergency response",
      "Only when the apparatus siren is operating",
      "At all times when riding in fire apparatus or operating power equipment",
      "Only for personnel seated in the rear of apparatus",
    ],
    answer: 2,
    explanation: "Hearing protection is required at all times while riding in fire apparatus or operating power equipment.",
    source: "Article 3 §3.4.27, p. 14",
  },
  {
    id: 11,
    topic: "Work rules",
    prompt: "The Firefighting Division's schedule averages how many hours per week over a 28-day period?",
    options: ["40", "48", "56", "72"],
    answer: 2,
    explanation: "Three shifts each average 56 hours per week over a 28-day period, using 24-hour duty periods.",
    source: "Article 3 §3.5.1, p. 15",
  },
  {
    id: 12,
    topic: "Work rules",
    prompt: "A Firefighting Division member taking sick leave must notify the District Chief and Company Officer during which window?",
    options: ["5:30-6:00 a.m.", "6:00-6:15 a.m.", "6:30-6:45 a.m.", "Before 7:00 a.m."],
    answer: 1,
    explanation: "Notification is required between 6:00 and 6:15 a.m. on the morning before the shift begins.",
    source: "Article 3 §3.5.18, p. 18",
  },
  {
    id: 13,
    topic: "Work rules",
    prompt: "Trade time must normally be approved by the District Chief and Fire Officer at least:",
    options: ["12 hours before", "24 hours before", "48 hours before", "One week before"],
    answer: 1,
    explanation: "Trade time requires approval at least 24 hours before it occurs.",
    source: "Article 3 §3.5.34(a), p. 20",
  },
  {
    id: 14,
    topic: "Work rules",
    prompt: "During a 24-hour shift, firefighting apparatus may normally be used to obtain groceries or pick up restaurant food how many times?",
    options: ["Once", "Twice", "Three times", "As often as needed within first due"],
    answer: 1,
    explanation: "The limit is two times per 24-hour shift; crews must remain in their first-due EMS territory and may not sit down to eat at the restaurant.",
    source: "Article 3 §3.6.35, p. 27",
  },
  {
    id: 15,
    topic: "Work rules",
    prompt: "Which statement about sleeping watch is correct?",
    options: [
      "It is permitted from 10:00 p.m. to 6:00 a.m.",
      "It transfers alarm responsibilities to Dispatch",
      "It is permitted from 11:00 p.m. to 7:00 a.m. but does not relieve watch responsibilities",
      "It is suspended only when the fire phone is out of service",
    ],
    answer: 2,
    explanation: "Sleeping watch is permitted from 11:00 p.m. to 7:00 a.m., but all alarm receipt and transmission duties remain in force.",
    source: "Article 3 §3.8.17, p. 35",
  },
  {
    id: 16,
    topic: "Fire operations",
    prompt: "Who is responsible for evaluating and continuously reevaluating risk throughout an incident?",
    options: ["The first-arriving driver", "The Incident Commander", "The Accountability Officer", "The senior firefighter on the attack line"],
    answer: 1,
    explanation: "Risk assessment is the IC's responsibility and continues for the full duration of the incident.",
    source: "Article 4 §4.1.1, p. 2",
  },
  {
    id: 17,
    topic: "Fire operations",
    prompt: "Under the residential fire attack guideline, a second alarm dispatches:",
    options: [
      "One engine and one ladder",
      "Two engines and one ladder",
      "Two engines and two ladders",
      "Three engines and one rescue company",
    ],
    answer: 1,
    explanation: "A second alarm dispatches two additional engine companies and one additional ladder company.",
    source: "Article 4 §4.1.2, p. 6",
  },
  {
    id: 18,
    topic: "Fire operations",
    prompt: "How should the first-arriving engine generally position at a structure fire?",
    options: [
      "Directly in front of the A side",
      "Past the structure, leaving the A side open for the ladder company",
      "At the nearest hydrant until assigned",
      "One block away in Level I staging",
    ],
    answer: 1,
    explanation: "The first engine positions past the structure to preserve the A side for the ladder company.",
    source: "Article 4 §4.1.2, p. 7",
  },
  {
    id: 19,
    topic: "Fire operations",
    prompt: "Until relieved by the next RIT crew, the second-arriving engine/quint should perform:",
    options: ["Ventilation", "RIT functions", "Salvage", "Accountability Officer duties"],
    answer: 1,
    explanation: "Its listed actions include establishing water supply, deploying a backup line, and performing RIT functions until relieved.",
    source: "Article 4 §4.1.2, p. 8",
  },
  {
    id: 20,
    topic: "Fire operations",
    prompt: "In RECEO VS, which pair is identified as actions of opportunity?",
    options: ["Rescue and exposures", "Confine and extinguish", "Ventilate and salvage", "Extinguish and overhaul"],
    answer: 2,
    explanation: "Rescue, exposures, confinement, extinguishment, and overhaul are sequential actions; ventilation and salvage are actions of opportunity.",
    source: "Article 4 §4.1.2, pp. 6-7",
  },
  {
    id: 21,
    topic: "Fire operations",
    prompt: "The offensive-versus-defensive guideline organizes decision-making around:",
    options: ["Life-Safety-Property", "Value-Time-Size", "Risk-Resources-Response", "Smoke-Heat-Flow"],
    answer: 1,
    explanation: "The guideline uses Value, Time, and Size. Its required fire-flow prompt is L × W ÷ 3.",
    source: "Article 4 §4.1.3, p. 10",
  },
  {
    id: 22,
    topic: "Fire operations",
    prompt: "A hydrant with a red bonnet indicates which rated flow?",
    options: ["1,500+ gpm", "1,000-1,499 gpm", "500-999 gpm", "Less than 500 gpm"],
    answer: 3,
    explanation: "Red indicates less than 500 gpm. Solid red hydrants or hydrants with a red bonnet are limited to refilling booster tanks under this guideline.",
    source: "Article 4 §4.1.12, p. 24",
  },
  {
    id: 23,
    topic: "Rescue & safety",
    prompt: "For swiftwater incidents, where does the warm zone begin?",
    options: ["At the water's edge", "5 feet from the water's edge", "15 feet from the water's edge", "25 feet from the water's edge"],
    answer: 2,
    explanation: "The warm zone begins 15 feet from the water's edge; the cold zone is anything greater than 15 feet away, and the hot zone is in the water.",
    source: "Article 4 §4.4.1, p. 55",
  },
  {
    id: 24,
    topic: "Rescue & safety",
    prompt: "At a trench collapse, the first-arriving apparatus should position at least how far from the trench?",
    options: ["50 feet", "75 feet", "100 feet", "150 feet"],
    answer: 2,
    explanation: "The first apparatus should stop at least 100 feet away; additional arriving units stage at least 150 feet away.",
    source: "Article 4 §4.4.2, p. 57",
  },
  {
    id: 25,
    topic: "Rescue & safety",
    prompt: "Initial KFD companies at a confined-space incident operate at which level?",
    options: ["Operations", "Technician", "Awareness", "Command"],
    answer: 2,
    explanation: "Initial companies function at the Awareness level and shall not enter. Entry is defined as breaking the plane of the opening.",
    source: "Article 4 §4.4.3, p. 59",
  },
  {
    id: 26,
    topic: "Rescue & safety",
    prompt: "When must each SCBA be tested and inspected?",
    options: [
      "Weekly and after a reported malfunction",
      "At the beginning of each shift and after each use",
      "At the end of each shift only",
      "Monthly by Logistics",
    ],
    answer: 1,
    explanation: "Each SCBA is inspected at the beginning of every shift, after every use, and whenever needed to restore ready condition.",
    source: "Article 4 §4.5.2, p. 64",
  },
  {
    id: 27,
    topic: "Fire operations",
    prompt: "In Level I staging, units other than the first engine, first ladder, and second engine should generally stage:",
    options: ["At the command post", "At the primary hydrant", "Approximately one block away", "At the nearest fire station"],
    answer: 2,
    explanation: "All other responding units stage uncommitted about one block away and await Command; units must not self-assign.",
    source: "Article 4 §4.5.3, p. 65",
  },
  {
    id: 28,
    topic: "Rescue & safety",
    prompt: "What is the apparatus air-horn evacuation signal?",
    options: ["One continuous blast", "Two long blasts", "Three repeated short blasts", "Five alternating short and long blasts"],
    answer: 2,
    explanation: "The evacuation signal is three repeated short air-horn blasts; a PAR should begin as soon as possible afterward.",
    source: "Article 4 §4.5.4, p. 67",
  },
  {
    id: 29,
    topic: "Rescue & safety",
    prompt: "After jumping clear of a vehicle involved with downed wires, occupants should shuffle at least how far away?",
    options: ["5 feet", "10 feet", "20 feet", "One apparatus length"],
    answer: 1,
    explanation: "Occupants should avoid simultaneous contact with vehicle and ground, then use small shuffle steps until at least 10 feet away from the vehicle or wires.",
    source: "Article 4 §4.5.5, p. 68",
  },
  {
    id: 30,
    topic: "Rescue & safety",
    prompt: "Companies responding to a potentially violent incident should initially stage:",
    options: ["Out of sight but within 100 feet", "At least one block away", "At the nearest hydrant", "Two blocks away in all cases"],
    answer: 1,
    explanation: "Companies stage at least one block away, advise Dispatch, and remain until KPD confirms the scene is secure and FD services are required.",
    source: "Article 4 §4.5.6, p. 70",
  },
];

type QuestionSeed = readonly [Topic, string, string, string, string, string, string, string];

const additionalSeeds: QuestionSeed[] = [
  ["Command & conduct", "In the absence of a written rule, what standing does a verbal order have?", "The same force and authority as a written rule or regulation", "It is advisory only", "It applies only during emergencies", "It expires at the end of the shift", "A verbal order carries the same force and standing as a written regulation or rule.", "Article 3 §3.1.3, p. 1"],
  ["Command & conduct", "May a member seek outside influence to get around a lawful Department order?", "No; outside influence may not be used to circumvent lawful orders", "Yes, for transfers only", "Yes, if the member disagrees with the order", "Only with union approval", "Members may not use individuals or organizations outside KFD to circumvent lawful orders, including transfer and promotion matters.", "Article 3 §3.1.4, p. 1"],
  ["Command & conduct", "How must members treat someone temporarily performing the duties of a higher rank?", "With the obedience, respect, and courtesy due that higher rank", "As their permanent lower rank", "As an advisor without command authority", "Only as directed by the Fire Chief", "A member temporarily assigned higher-rank duties receives the respect and obedience required for that rank.", "Article 3 §3.2.8, p. 3"],
  ["Command & conduct", "If someone in a member's chain of command requests a statement about a job-related incident, the member must:", "Provide the statement", "Decline unless represented by an attorney", "Wait for a written subpoena", "Refer the request to Dispatch", "Members shall give statements concerning job-related incidents when requested within their chain of command.", "Article 3 §3.2.12, p. 4"],
  ["Command & conduct", "Which conduct is prohibited on Department premises whether a member is on or off duty?", "Fighting, horseplay, and loud, abusive, or profane language", "Quiet personal study", "Approved physical training", "Station tours", "The conduct rule applies on Department premises or property whether the member is on or off duty.", "Article 3 §3.2.14, p. 4"],
  ["Command & conduct", "Unless official duties require otherwise, firearms inside Fire Department buildings are:", "Prohibited", "Allowed if unloaded", "Allowed in personal lockers", "Allowed with a Tennessee carry permit", "Employees may not bring firearms or other weapons into KFD buildings unless specifically required by official duties.", "Article 3 §3.2.18(b), p. 5"],
  ["Command & conduct", "When may emergency equipment or personnel leave their first-due EMS territory while on duty?", "For official Department business, or with District Chief permission when coverage is maintained", "Whenever the Company Officer agrees", "Only after 5:00 p.m.", "For any personal errand lasting under 15 minutes", "Leaving the first-due EMS territory requires official business or District Chief permission to ensure coverage.", "Article 3 §3.2.20, p. 5"],
  ["Command & conduct", "Members must report to work free from:", "The influence and odor of alcohol and other drugs", "Prescription medication of any kind", "Caffeine", "All over-the-counter medication", "The rule requires members to report free from both the influence and odor of alcohol and other drugs.", "Article 3 §3.2.26, p. 6"],
  ["Command & conduct", "A safety-sensitive employee using prescription medication that may impair duty performance must:", "Disclose the use", "Take annual leave automatically", "Report only after a performance problem", "Tell only a coworker", "Potentially impairing prescription medication must be disclosed; a physician's statement may be required.", "Article 3 §3.2.28, p. 6"],
  ["Command & conduct", "Prior approval from whom is required when a member wants City resources for outside training or to represent KFD?", "The Fire Chief", "The Company Officer only", "The Training Captain only", "The Civil Service Board", "The Fire Chief's prior approval is required for City resources or official KFD representation.", "Article 3 §3.2.30, p. 6"],
  ["Command & conduct", "A candidate for elected office wants to visit a station for campaign purposes. What is required?", "Prior Fire Chief approval, no operational interference, and equal access for candidates", "Only Company Officer approval", "A City-funded reception", "Mandatory member attendance", "Campaign visits require Chief approval, must be open to all candidates, may not use City funds, and cannot coerce attendance.", "Article 3 §3.2.31, p. 7"],
  ["Command & conduct", "Information learned while on duty may be used to advance off-duty employment:", "Never", "Only with a supervisor's verbal approval", "Only when no City equipment is used", "After the member's shift ends", "Members may not use on-duty information or their KFD position for off-duty economic advantage.", "Article 3 §3.2.32, p. 7"],
  ["Command & conduct", "Before recording a communication with another KFD member, a member needs prior approval from:", "The Fire Chief and the member being recorded", "Only the Company Officer", "Only the person being recorded", "The City Law Department", "Both the Fire Chief and the member being recorded must approve the recording in advance.", "Article 3 §3.2.33, p. 7"],
  ["Command & conduct", "Official Department business should be shared with:", "Only those for whom it is intended, under established procedures", "Any City employee", "Any member of the news media", "Family members if names are omitted", "Official business is confidential and is disseminated only to intended recipients under Department procedures.", "Article 3 §3.2.34, p. 7"],
  ["Command & conduct", "Who may normally provide emergency information to the news media?", "The Community Relations Officer or designee, or an Assistant Chief or higher at the scene", "Any member who witnessed the event", "The apparatus driver", "Only the Incident Safety Officer", "Media information is restricted to the Community Relations Officer/designee or an Assistant Chief or higher at an emergency.", "Article 3 §3.2.36, p. 8"],
  ["Command & conduct", "May a Department member give the news media a damage estimate for a wreck or fire?", "No", "Yes, if clearly labeled preliminary", "Yes, with Company Officer approval", "Only for vehicle fires", "No Department member may give damage estimates to the news media regarding wrecks or fires.", "Article 3 §3.2.37, p. 8"],
  ["Command & conduct", "Which rank may issue a Counseling Form for a rule infraction?", "Fire Officers and above", "Assistant Chiefs and above only", "Deputy Chiefs and above only", "The Fire Chief only", "Fire Officers and above may administer a Counseling Form.", "Article 3 §3.3.3, p. 9"],
  ["Command & conduct", "Which rank may issue a written reprimand?", "Assistant Chiefs and above", "Fire Officers and above", "Master Firefighters and above", "Only the Fire Chief", "Written reprimands are assigned to Assistant Chiefs and above.", "Article 3 §3.3.3, p. 9"],
  ["Command & conduct", "Which disciplinary actions are specifically authorized for the Fire Chief?", "Suspension, reduction in rank, and termination", "Counseling only", "Oral reprimand only", "Transfer only", "The Chief may impose suspension, reduction in rank, or termination under the cited Civil Service rules.", "Article 3 §3.3.3, p. 9"],
  ["Command & conduct", "Why may a supervisor relieve a member from duty?", "To prevent Department embarrassment or avoid potential conflict", "Only after a criminal conviction", "Only when overtime is unavailable", "To resolve a trade-time request", "Supervisors may relieve members to prevent embarrassment to the Department or avoid potential conflict.", "Article 3 §3.3.4, p. 9"],
  ["Response readiness", "Who may drive KFD apparatus on an emergency response?", "A firefighter properly trained and whose driving skills were assessed by the Training Academy and Health & Safety Officer or designee", "Any member with a Class D license", "Any Senior Firefighter", "Only a Fire Officer", "Emergency apparatus driving requires both proper training and a driving-skills assessment.", "Article 3 §3.4.1, p. 10"],
  ["Response readiness", "Apparatus returning from a call should:", "Return directly to quarters unless on official assignment", "Stop for personal errands if the crew agrees", "Remain in service away from quarters for one hour", "Return by the longest available route", "Emergency and non-emergency units respond and return directly unless on official assignment, subject to the food-trip exception.", "Article 3 §3.4.3, p. 10"],
  ["Response readiness", "May a seatbelt be unbuckled to don PPE while apparatus is moving?", "No", "Yes, below 25 mph", "Yes, with officer approval", "Only in the rear-facing seats", "Seatbelts may not be unbuckled to don PPE while traveling.", "Article 3 §3.4.4, p. 10"],
  ["Response readiness", "Vehicle spotlights should be used for:", "Building numbers, street markers, and fire-ground needs", "Directing civilian traffic", "Signaling apparatus through intersections", "Replacing red warning lights", "Spotlights are not traffic-control aids; they are used to locate numbers/markers and on the fire ground.", "Article 3 §3.4.6, p. 10"],
  ["Response readiness", "Which situation requires an emergency vehicle driver to come to a complete stop?", "A blind intersection", "Every green traffic signal", "Every railroad crossing regardless of conditions", "Any curve with limited shoulder space", "Complete stops are required when directed by law enforcement, at blind intersections, when all traffic lanes cannot be accounted for, and for school buses with flashing lights.", "Article 3 §3.4.9, p. 11"],
  ["Response readiness", "Who must be notified when a sprinkler or standpipe system has been activated at a fire?", "The Fire Marshal or designee", "The Logistics Officer", "The Training Academy", "The City Purchasing Office", "The Officer-in-Charge is responsible for informing the Fire Marshal or designee.", "Article 3 §3.4.13, p. 12"],
  ["Response readiness", "What hose load is required on pre-connected attack lines?", "Flat Load", "Minuteman Load", "Triple Layer Load", "Accordion Load", "Article 3 specifies the Flat Load for pre-connected attack lines.", "Article 3 §3.4.18, p. 13"],
  ["Response readiness", "Does the arrival of a superior officer erase a subordinate member's responsibility for earlier actions?", "No", "Yes, immediately", "Only during a second alarm", "Only if command is transferred by radio", "Arrival of a superior officer does not relieve subordinate members of responsibility for previous actions.", "Article 3 §3.4.19, p. 13"],
  ["Response readiness", "Company Officers at incidents should keep company personnel:", "Intact and supervised", "Split among as many crews as possible", "At the command post", "With the first-arriving ladder", "Company Officers remain with their units, supervise the work, and keep personnel intact.", "Article 3 §3.4.20, p. 13"],
  ["Response readiness", "When practical and resources are available, booster tanks and tankers should be refilled:", "On the fire ground", "Only at the station", "After returning to service", "At the Training Center", "Article 3 directs refilling on the fire ground when practical and supported by resources.", "Article 3 §3.4.23, p. 13"],
  ["Response readiness", "A company is dispatched while in service away from the station. What must it report immediately?", "Its location to Dispatch", "Its fuel level", "Its staffing seniority", "Its expected return time to quarters", "Reporting location lets Dispatch anticipate travel direction and warn of cross-street conflicts.", "Article 3 §3.4.25, p. 14"],
  ["Work rules", "What is the minimum staffing for each Engine, Quint, and Ladder company?", "Three firefighters", "Two firefighters", "Four firefighters", "Five firefighters", "Each Engine, Quint, and Ladder company is staffed with at least three firefighters.", "Article 3 §3.5 Staffing, p. 15"],
  ["Work rules", "What is the minimum staffing for Rescue One and Haz-Mat?", "Two specially trained firefighters each", "One officer each", "Three firefighters each", "Four members shared between both units", "Rescue One and Haz-Mat each require at least two specially trained firefighters.", "Article 3 §3.5 Staffing, p. 15"],
  ["Work rules", "How many District Chiefs must each shift have at minimum?", "Three", "Two", "Four", "Five", "Each shift is staffed with a minimum of three District Chiefs.", "Article 3 §3.5 Staffing, p. 15"],
  ["Work rules", "Who may initiate Emergency Personnel Recall?", "The Fire Chief or either Deputy Fire Chief", "Any Company Officer", "Dispatch alone", "The senior firefighter at any station", "Recall may be initiated by the Fire Chief, Deputy Chief of Operations, or Deputy Chief of Administration.", "Article 3 §3.5 Emergency Recall, p. 15"],
  ["Work rules", "A change in address or phone number must be reported to the Company Officer within:", "24 hours", "48 hours", "Seven days", "By the end of the month", "The Company Officer must be notified within 24 hours and the change filed with Administration by the end of the next business day.", "Article 3 §3.5 Emergency Recall, p. 15"],
  ["Work rules", "A member living in Knox County who is recalled has how long to report?", "One hour from the call", "30 minutes", "90 minutes", "Two hours", "Members living in Knox County have one hour from the recall to report to their duty assignment.", "Article 3 §3.5 Emergency Recall, p. 15"],
  ["Work rules", "When does the normal 24-hour duty period begin for firefighting personnel?", "7:00 a.m.", "6:00 a.m.", "8:00 a.m.", "12:00 noon", "The firefighting duty period runs from 7:00 a.m. to 7:00 a.m. the next day.", "Article 3 §3.5.2, p. 16"],
  ["Work rules", "When does the normal duty period begin for firefighting Chief Officers?", "6:00 a.m.", "7:00 a.m.", "5:30 a.m.", "8:00 a.m.", "Chief Officers normally work from 6:00 a.m. to 6:00 a.m. the next day.", "Article 3 §3.5.3, p. 16"],
  ["Work rules", "After being contacted to float, a member must report within:", "30 minutes", "10 minutes", "One hour", "Two hours", "A float assignment requires reporting 30 minutes after contact.", "Article 3 §3.5.6, p. 16"],
  ["Work rules", "A member doubled from home must report within:", "One hour after contact", "30 minutes", "90 minutes", "At the next shift change", "The doubled-from-home reporting time is one hour.", "Article 3 §3.5.6, p. 16"],
  ["Work rules", "A member doubled from a fire station must report within:", "30 minutes after contact", "One hour", "10 minutes", "Two hours", "The doubled-from-station reporting time is 30 minutes.", "Article 3 §3.5.6, p. 16"],
  ["Work rules", "A member who commits to work a special event may also:", "Neither be on call nor work a double day", "Work a double day only", "Remain on call only", "Choose either on-call or double-day status", "Special-event commitments cannot overlap with on-call status or a double day.", "Article 3 §3.5.6, p. 16"],
  ["Work rules", "A member who cannot begin responding within how many minutes of notification cannot be on call?", "10 minutes", "5 minutes", "20 minutes", "30 minutes", "On-call members must be able to begin responding within 10 minutes.", "Article 3 §3.5.6, p. 16"],
  ["Work rules", "Members assigned to 24-hour shifts take annual leave in which increments?", "12 or 24 hours", "4 or 8 hours", "8 or 16 hours", "24 hours only", "Annual leave is taken in 12- or 24-hour increments, with no more than four 12-hour shifts per year.", "Article 3 §3.5.9, pp. 17-18"],
  ["Work rules", "When annual-leave requests conflict, what receives first priority?", "The request for the greatest number of 24-hour shifts", "The earliest request timestamp", "The member with the most overtime", "The member at the busiest station", "Priority first goes to the greatest number of 24-hour shifts; remaining conflicts are resolved by rank, time in grade, then seniority.", "Article 3 §3.5.11, p. 18"],
  ["Work rules", "How much sick leave may a member on a 56-hour week use annually for a spouse, partner, child, or parent's medical needs?", "56 hours", "40 hours", "72 hours", "One 24-hour shift", "The family-medical sick-leave maximum is 56 hours for a 56-hour-week member.", "Article 3 §3.5.19, p. 19"],
  ["Work rules", "An absence of how long due to personal or immediate-family illness triggers FMLA forms?", "Ten or more days, or five 24-hour shifts", "Three days", "Seven calendar days", "Two 24-hour shifts", "FMLA forms are required at ten or more days, defined for shift personnel as five 24-hour shifts.", "Article 3 §3.5.19, p. 19"],
  ["Work rules", "On the first shift back after sick leave, a member must:", "Complete and sign a Request for Leave form", "Report to the Training Center", "Complete a trade-time form", "Submit a new annual-leave request", "The Request for Leave form is completed and forwarded to Administration on the first returning shift.", "Article 3 §3.5.23, p. 20"],
  ["Work rules", "A job-related injury must first be reported:", "Immediately to the supervisor", "At the end of the shift to Logistics", "Within 72 hours to Payroll", "At the next monthly safety meeting", "On-the-job injuries are reported immediately to the supervisor and documented on the proper online accident report.", "Article 3 §3.5.26, p. 20"],
  ["Work rules", "A member may normally trade time with another member of equal rank and capabilities for no more than:", "Thirty 12-hour days per year", "Twelve 24-hour days per year", "Twenty 12-hour days per year", "Unlimited days with officer approval", "The normal annual maximum is thirty 12-hour trade days.", "Article 3 §3.5.34(b), p. 21"],
  ["Work rules", "Swapped time must be repaid within:", "One year of the original swap", "30 days", "Six months", "The same calendar year", "Trade time is repaid within one year from the date of the original swap.", "Article 3 §3.5.34(c), p. 21"],
  ["Work rules", "If jury duty lasts less than three hours in a day, the employee must:", "Return to work or use leave for the remaining work hours", "Take the rest of the day as paid civil leave", "Use sick leave for the full day", "Report to Administration only", "Jury service under three hours is civil leave, after which the employee returns or uses leave for the balance.", "Article 3 §3.5.35, p. 22"],
  ["Work rules", "Failure to report for duty without notifying an Assistant Chief, Deputy Chief, or Chief for how long may result in termination?", "30 calendar days", "10 days", "14 days", "60 days", "A member who neither reports nor provides the required notification for 30 calendar days is subject to termination.", "Article 3 §3.5.37, p. 23"],
  ["Work rules", "Which station-cleaning task is assigned to Monday?", "Clean the apparatus floor", "Wash apparatus tools and compartments", "Clean HVAC components", "Thoroughly clean the kitchen", "Monday's added cleaning task is the apparatus floor.", "Article 3 §3.6.3, p. 24"],
  ["Work rules", "Which station-cleaning task is assigned to Tuesday?", "Wash or clean apparatus tools, equipment, and compartments", "Clean the apparatus floor", "Clean HVAC components", "Lawn and driveway care", "Tuesday focuses on apparatus tools, equipment, and compartments.", "Article 3 §3.6.3, p. 24"],
  ["Work rules", "Which station-cleaning task is assigned to Wednesday?", "Vacuum or clean HVAC components", "Thoroughly clean the kitchen", "Wash apparatus tools", "Mow the lawn", "Wednesday is assigned to HVAC registers, grills, ducts, vents, and related components.", "Article 3 §3.6.3, p. 24"],
  ["Work rules", "Which station-cleaning task is assigned to Thursday?", "Thorough kitchen cleaning", "Apparatus-floor cleaning", "HVAC cleaning", "Outside lawn care", "Thursday is the thorough kitchen-cleaning day.", "Article 3 §3.6.3, p. 24"],
  ["Work rules", "Which station-cleaning task is assigned to Friday?", "Seasonal lawn care, outside trash policing, and driveway cleaning as needed", "Kitchen cleaning", "Apparatus compartment cleaning", "HVAC cleaning", "Friday covers the lawn during season and other outside/driveway care.", "Article 3 §3.6.3, p. 24"],
  ["Work rules", "Without a temporary illness or injury and Company Officer permission, beds may not be occupied between:", "7:00 a.m. and 12:00 noon", "6:00 a.m. and 10:00 a.m.", "12:00 noon and 5:00 p.m.", "7:00 p.m. and 11:00 p.m.", "Beds are restricted from 7:00 a.m. to noon unless the stated exception applies.", "Article 3 §3.6.6, p. 25"],
  ["Work rules", "Visitors may lounge or sleep in a station only with permission from:", "The District Chief on duty", "Any firefighter", "The watch-duty member", "The Logistics Officer", "Visitor lounging or sleeping requires the on-duty District Chief's permission.", "Article 3 §3.6.14, p. 26"],
  ["Work rules", "A ride-along requires approval from whom?", "The Company Officer and the Fire Chief or a Deputy Chief", "The Company Officer only", "Dispatch and the Training Academy", "The District Chief only", "Ride-alongs require the listed approvals and signed waivers received by Administration before the ride.", "Article 3 §3.6.19, p. 26"],
  ["Work rules", "When may recreational activities such as television, exercise, or extra study begin?", "After work assignments, daily fire school, and training are complete", "After noon regardless of assignments", "Only after 7:00 p.m.", "Whenever the station is in service", "The Company Officer must ensure assignments and training are completed first.", "Article 3 §3.6.22, p. 27"],
  ["Work rules", "A firefighter assigned to float has how long to reach the designated assignment?", "30 minutes", "15 minutes", "One hour", "Until the next alarm", "The floating member has 30 minutes to reach the assigned station.", "Article 3 §3.6.28, p. 27"],
  ["Work rules", "Paramedics assigned to ALS companies should be floated only when:", "More than one paramedic is available on that unit", "The unit has a Master Firefighter", "The station is outside its first due", "Dispatch approves by radio", "The policy protects ALS staffing by limiting paramedic floating when only one is available.", "Article 3 §3.6.30, p. 27"],
  ["Work rules", "If an ALS company's paramedic is off and no qualified person can float in, the company should:", "Respond as a basic first responder unit and notify Dispatch at shift change", "Go out of service for the entire shift", "Respond as ALS with the senior member in charge", "Request a mutual-aid medic for every call", "The company operates as a basic first responder unit and Dispatch is notified at shift change.", "Article 3 §3.6.31, p. 28"],
  ["Work rules", "How should personnel answer a station phone?", "State the station, rank, and last name", "State only the apparatus number", "State first and last name only", "Answer without identifying the station", "The required answer identifies station, rank, and last name and remains courteous.", "Article 3 §3.6.34, p. 28"],
  ["Work rules", "Officers direct emergency operations until:", "An appropriate officer of equal or higher rank arrives and command is officially transferred", "Any Chief Officer arrives", "Dispatch announces a second alarm", "The first tactic is completed", "Command continues until an appropriate officer arrives and an official transfer occurs.", "Article 3 §3.6.36(a)(4), p. 29"],
  ["Work rules", "After a transfer, personal belongings should normally be removed from the old locker within:", "Three shifts", "One shift", "Seven calendar days", "30 days", "The normal deadline is three shifts unless circumstances such as illness or injury prevent it.", "Article 3 §3.6.37, p. 30"],
  ["Work rules", "Before sending a KFDGRP group email, most members need permission from:", "The Administrative Office", "Dispatch", "The Company Officer", "Information Systems", "Administration must approve group emails, except for Division Heads or approved designees.", "Article 3 §3.7.4, p. 32"],
  ["Work rules", "How often must shift personnel check email while on duty?", "Daily", "At least twice each shift", "Weekly", "Only when directed", "All shift personnel check email daily while on duty.", "Article 3 §3.7.5, p. 32"],
  ["Work rules", "How often should Shift Assistant Chiefs and Fire Officers check email while on duty?", "At least twice daily, preferably at shift start and after 1700", "Once at shift change", "Every four hours", "Only after 1700", "The rule calls for at least two checks, preferably at the start and after 1700.", "Article 3 §3.7.5, p. 32"],
  ["Work rules", "Station duty watch is maintained during which period?", "Continuously from 7:00 a.m. to 7:00 a.m.", "Only from 7:00 p.m. to 7:00 a.m.", "Only during sleeping hours", "From 6:00 a.m. to midnight", "Each station maintains a 24-hour duty watch from 7:00 a.m. to 7:00 a.m.", "Article 3 §3.8.1, p. 33"],
  ["Work rules", "An urgent fax or KFDGRP email received on watch should be forwarded immediately to:", "The highest-ranking officer working at the station", "Every member in the Department", "The Logistics Officer", "The next shift's watch member", "Urgent messages are sent immediately to the highest-ranking officer at the station.", "Article 3 §3.8.4(c), p. 33"],
  ["Work rules", "When is the station emergency generator checked and documented?", "Every Monday", "The first day of each month", "Every Friday", "After every alarm", "The watch-duty member checks it every Monday and documents the check in FireHouse.", "Article 3 §3.8.13, p. 34"],
  ["Work rules", "When leaving KFD for a reason other than retirement, identifying Department items must be returned to Logistics within:", "Five business days", "24 hours", "Ten calendar days", "30 days", "Issued PPE and identifying KFD items are returned within five business days of separation.", "Article 3 §3.9.9, p. 37"],
  ["Work rules", "Class A service Maltese Crosses represent:", "One cross for each five years of service", "One cross for each promotion", "One cross for each ten years", "One cross for each commendation", "The Class A coat uses one Maltese Cross for each five years, with half-period additions permitted.", "Article 3 §3.9.13, p. 38"],
  ["Work rules", "What cap is specified for a Master Firefighter with the Class A uniform?", "Navy blue top with a silver band", "White top with a gold band", "Navy blue top with a black band", "White top with black braid", "Master and Senior Firefighters wear a navy blue cap top with a silver band.", "Article 3 §3.9.15(A), p. 38"],
  ["Work rules", "How many sleeve stripes identify a Master Firefighter on the Class A coat?", "Two silver stripes", "One silver stripe", "Two gold stripes", "Three silver stripes", "A Master Firefighter wears two silver stripes on both sleeves.", "Article 3 §3.9.15(C), p. 39"],
  ["Work rules", "Which uniform is not permitted for EMS events?", "Class D", "Class B", "Class C", "Class A", "Class C is required for EMS events, with Class B permitted as a substitute; Class D is not permitted.", "Article 3 §3.9.17, p. 40"],
  ["Work rules", "Sideburns may be no wider than:", "1 1/4 inches", "1/2 inch", "2 inches", "The width of the ear", "Sideburns must be neat, stay above the lowest ear point, and not exceed 1 1/4 inches in width.", "Article 3 §3.10.3, p. 43"],
  ["Work rules", "A moustache may extend beyond the corner of the mouth by no more than:", "A vertical line 1/2 inch from the corner", "One inch", "The width of the nose", "It may not reach the corner at all", "The moustache boundaries are one-half inch from and below the mouth corner and must not interfere with the facepiece seal.", "Article 3 §3.10.4, p. 43"],
  ["Work rules", "What is the rule for beards and goatees?", "They are prohibited", "They are allowed if under 1/4 inch", "Goatees are allowed but beards are not", "They are allowed off the fire ground", "The remainder of the face must be clean-shaven, prohibiting beards and goatees.", "Article 3 §3.10.5, p. 44"],
  ["Work rules", "Female members' hair may be no longer than:", "The top of the shoulders in a normal standing posture", "The bottom of the collar", "The middle of the back", "Two inches below the shoulders", "The stated maximum is the top of the shoulders when standing normally.", "Article 3 §3.10.6, p. 44"],
  ["Work rules", "Which tattoo restriction is correct?", "Face, head, and neck tattoos are prohibited, and none may show with Class A", "All tattoos are prohibited", "Only hand tattoos are prohibited", "Tattoos may show with Class A if covered by makeup", "The policy prohibits tattoos on the face, head, or neck and any visible tattoo with the Class A uniform.", "Article 3 §3.10.9, p. 44"],
  ["Response readiness", "After each use, fire hose and couplings must be:", "Cleaned with mild soap and water, inspected, and reloaded or stored", "Sent to Logistics automatically", "Dried for 72 hours before inspection", "Cleaned with a solvent", "All hose, including couplings, is cleaned, inspected, and returned to ready storage after use.", "Article 3 §3.11.3, p. 46"],
  ["Response readiness", "How tight should fire-hose couplings be made?", "Hand tight, except booster hose", "Wrench tight in all cases", "One full turn past hand tight", "Finger tight only", "Couplings are hand tight except for booster hose.", "Article 3 §3.11.6, p. 46"],
  ["Response readiness", "When are emergency apparatus checked for readiness?", "Each morning by the oncoming shift", "Weekly by Logistics", "At the end of each month", "Only after a mechanical problem", "The oncoming shift performs the morning readiness check and documents it on the Daily Vehicle/SCBA Checklist.", "Article 3 §3.12.2, p. 47"],
  ["Response readiness", "Who is responsible for the monthly apparatus tool and equipment inventory on the first day of the month?", "The Company Officer of the shift working that day", "The District Chief from the prior shift", "Logistics staff only", "The apparatus driver from every shift", "The working Company Officer or subordinate completes the inventory and forwards the forms.", "Article 3 §3.12.3, p. 47"],
  ["Response readiness", "On which day each month should ladder aerial devices be extended, cleaned, and have the waterway lubricated?", "The tenth day", "The first day", "The fifteenth day", "The last day", "The ladder-maintenance task is assigned to the tenth day of each month.", "Article 3 §3.12.5, p. 47"],
  ["EMS & HazMat", "At a medical call, which crew member is in charge of patient care?", "The member with the highest level of medical certification", "The apparatus driver", "The most senior firefighter regardless of certification", "The first member to contact the patient", "The highest medically certified crew member leads patient care.", "Article 4 §4.2.1, PDF p. 25"],
  ["EMS & HazMat", "When may a KFD crew leave a patient with another crew?", "Only after giving a patient report", "As soon as the ambulance arrives", "After loading equipment", "Only with Dispatch approval", "The KFD crew remains with the patient until care and a patient report are transferred to the ambulance crew.", "Article 4 §4.2.1, PDF p. 25"],
  ["EMS & HazMat", "After a medical response, equipment used should be:", "Replaced and obtained from the ambulance crew whenever possible", "Left with the patient", "Replaced only at the station", "Discarded regardless of condition", "Crews replace used equipment and should obtain replacement items from the ambulance crew when possible.", "Article 4 §4.2.1, PDF p. 25"],
  ["EMS & HazMat", "Within a unified EMS command, who develops strategic decisions and orders and releases resources?", "The Incident Commander", "The Triage Officer", "The Treatment Officer", "The Transportation Officer", "The Incident Commander develops EMS strategy and is responsible for ordering and releasing resources.", "Article 4 §4.2.2, PDF p. 26"],
  ["EMS & HazMat", "What is the Medical Officer's primary EMS command function?", "Oversee triage, treatment, and transportation logistics", "Provide all hands-on treatment", "Coordinate only ambulance destinations", "Maintain the incident radio log", "The Medical Officer manages the overall logistics of triage, treatment, and transportation.", "Article 4 §4.2.2, PDF p. 26"],
  ["EMS & HazMat", "What is the Treatment Officer responsible for?", "Stabilization and treatment of patients at the emergency scene", "Triage-tag distribution only", "Patient transportation records", "Hazard-zone control", "The Treatment Officer supervises on-scene patient stabilization and treatment.", "Article 4 §4.2.2, PDF p. 26"],
  ["EMS & HazMat", "What is the Medical Supply Officer responsible for?", "Acquiring and staging medical equipment and supplies", "Assigning triage categories", "Selecting hospitals", "Establishing HazMat zones", "The Medical Supply Officer obtains and stages appropriate medical equipment and supplies.", "Article 4 §4.2.2, PDF p. 26"],
  ["EMS & HazMat", "What is the Transportation Officer responsible for?", "Coordinating patient transportation and maintaining destination and transport records", "Treating red-tag patients", "Establishing the treatment area", "Managing station coverage", "The Transportation Officer coordinates movement and tracks destination/transport data.", "Article 4 §4.2.2, PDF p. 26"],
  ["EMS & HazMat", "What is the Triage Officer responsible for?", "Managing and coordinating triage of all patients", "Ordering additional alarms", "Operating the treatment area", "Selecting the staging hydrant", "The Triage Officer manages triage and coordinates assigned teams.", "Article 4 §4.2.2, PDF p. 26"],
  ["EMS & HazMat", "Small amounts of human tissue found during blood cleanup should be:", "Double-bagged and disposed of in the bio bag at the station", "Flushed into a storm drain", "Placed in regular station trash unbagged", "Left for property owners", "Small tissue is collected, double-bagged, and placed in the station bio bag.", "Article 4 §4.2.3, PDF p. 27"],
  ["EMS & HazMat", "What bleach-to-water solution is specified for neutralizing blood on a street or sidewalk?", "1 part bleach to 10 parts water", "1 part bleach to 1 part water", "1 part bleach to 5 parts water", "Water only", "The guideline specifies a 1:10 bleach-to-water concentration for roadway blood cleanup.", "Article 4 §4.2.3, PDF p. 27"],
  ["EMS & HazMat", "At every HazMat incident, establishing Incident Command is:", "Required by federal law and not optional", "Optional below a second alarm", "Required only when evacuation occurs", "The responsibility of law enforcement", "Article 4 states that HazMat Incident Command is required by federal law.", "Article 4 §4.3.1, PDF p. 30"],
  ["EMS & HazMat", "Which HazMat zone contains the contamination and is normally the incident's smallest zone?", "Hot Zone", "Warm Zone", "Cold Zone", "Staging Zone", "The Hot Zone surrounds the incident, contains contamination, and is typically the smallest zone.", "Article 4 §4.3.1, PDF p. 28"],
  ["EMS & HazMat", "What is the primary purpose of the HazMat Warm Zone?", "Support personnel and equipment exiting the Hot Zone and perform decontamination", "House command and media", "Provide public parking", "Store clean reserve apparatus", "The Warm Zone supports Hot-Zone operations and decontamination.", "Article 4 §4.3.1, PDF pp. 28-33"],
  ["EMS & HazMat", "Where are the Incident Commander, supporting agencies, staging, and clean support personnel located at a HazMat incident?", "Cold Zone", "Hot Zone", "Warm Zone", "Decontamination corridor", "The Cold Zone is the safe support area outside contamination.", "Article 4 §4.3.1, PDF p. 33"],
  ["EMS & HazMat", "For extensive HazMat decontamination, the IC appoints a:", "Decontamination Officer", "Transportation Officer", "Staging Officer", "Water Supply Officer", "The IC appoints a Decontamination Officer to manage the required decon process.", "Article 4 §4.3.1, PDF p. 33"],
  ["EMS & HazMat", "May personnel or equipment leave the HazMat Hot Zone without passing through decontamination?", "No", "Yes, with IC approval", "Yes, if no visible product is present", "Only apparatus may bypass decon", "Nothing leaves the Hot Zone without passing through the decontamination process.", "Article 4 §4.3.1, PDF pp. 32-33"],
  ["EMS & HazMat", "When may medical treatment occur before a contaminated patient is decontaminated?", "When immediate treatment is required", "Never", "Only at the receiving hospital", "Only after law enforcement approval", "Decon normally comes first, but immediate medical necessity can delay it; treatment personnel then use protective clothing.", "Article 4 §4.3.1, PDF p. 34"],
  ["EMS & HazMat", "At a low-threat unknown-powder incident, the HazMat Team may use which screening kit?", "A basic 20/20 kit", "A Class A foam kit", "A chlorine repair kit", "A combustible-gas-only meter", "The low-threat unknown-powder procedure permits the basic 20/20 kit to rule out a biological agent.", "Article 4 §4.3.6, PDF p. 50"],
  ["EMS & HazMat", "What carbon-monoxide reading is the OSHA permissible exposure limit for an 8-hour period in a residential structure?", "50 ppm", "35 ppm", "100 ppm", "10 ppm", "The guideline lists 50 ppm over eight hours for residential structures.", "Article 4 §4.3.7, PDF p. 51"],
  ["EMS & HazMat", "What carbon-monoxide reading is the OSHA permissible exposure limit for an 8-hour period in a commercial structure?", "35 ppm", "50 ppm", "100 ppm", "15 ppm", "The guideline lists 35 ppm over eight hours for commercial structures.", "Article 4 §4.3.7, PDF p. 51"],
  ["EMS & HazMat", "When a CO reading exceeds 100 ppm, interior activity is permitted only while wearing:", "Full SCBA", "An N95 respirator", "Turnout gear without SCBA", "No respiratory protection if the visit is brief", "No activities are allowed inside above 100 ppm unless personnel wear full SCBA.", "Article 4 §4.3.7, PDF p. 52"],
  ["Rescue & safety", "Who should establish command at a swiftwater or flooding incident?", "The first-arriving unit", "Only the Swiftwater Team", "The last-arriving District Chief", "Law enforcement", "The first-arriving unit establishes command and begins the initial size-up.", "Article 4 §4.4.1, PDF p. 55"],
  ["Rescue & safety", "What is the preferred order of swiftwater rescue options from lower to higher risk?", "Talk, Reach, Throw, Row, Helo, Go", "Go, Helo, Row, Throw, Reach, Talk", "Reach, Talk, Go, Row, Throw, Helo", "Throw, Row, Go, Talk, Reach, Helo", "The rescue-options sequence progresses from Talk through Go as risk increases.", "Article 4 §4.4.1, PDF p. 56"],
  ["Rescue & safety", "At a trench collapse, initial KFD companies operate at what level and may they enter an unsafe trench?", "Awareness level; they shall not enter", "Operations level; entry is allowed", "Technician level; entry is mandatory", "Command level; entry depends on seniority", "Initial companies operate at Awareness and do not enter an unsafe trench or excavation.", "Article 4 §4.4.2, PDF p. 57"],
  ["Command & conduct", "Who is the ultimate authority at the top of KFD's chain of command?", "The Fire Chief", "The senior Shift Commander", "The Deputy Chief of Operations", "The Civil Service Board", "Article 3 identifies the Fire Chief as the ultimate authority in the Department chain of command.", "Article 3 §3.1.1, p. 1"],
  ["Command & conduct", "Must a lawful order from a superior officer be obeyed when that officer is not the member's direct supervisor?", "Yes", "No", "Only during emergencies", "Only after the direct supervisor confirms it", "All lawful orders from superior officers must be obeyed, whether or not the officer is the member's immediate supervisor.", "Article 3 §3.1.5, p. 2"],
  ["Command & conduct", "Which response to a supervisor's order is prohibited?", "Verbal abuse or unreasonable questioning that delays or prevents the work", "Requesting written clarification of a possibly illegal order", "Reporting a conflicting prior order", "Using the established grievance process", "Members may not verbally abuse supervisors, unreasonably question orders, or fail to perform requested work.", "Article 3 §3.1.8, p. 2"],
  ["Command & conduct", "KFD's ordinary rules of good conduct apply to members:", "Both on and off duty", "Only while on duty", "Only while in uniform", "Only on City property", "Members are governed by reasonable standards of conduct on and off duty and may not bring discredit upon KFD or the City.", "Article 3 §3.2.2, p. 3"],
  ["Command & conduct", "Members are expected to maintain what level of job competency?", "Enough to properly perform their duties and responsibilities", "Only the minimum needed for annual evaluation", "The same level held at graduation", "Only competencies specifically tested that month", "Members must maintain sufficient competency and perform with high efficiency and effectiveness.", "Article 3 §3.2.3, p. 3"],
  ["Command & conduct", "A matter comes to a member's attention that affects Department welfare. Who should be notified promptly?", "The member's immediate supervisor", "The news media", "Any off-duty Chief Officer", "The Civil Service Board", "Matters affecting Department welfare must be promptly reported to the immediate supervisor.", "Article 3 §3.2.5, p. 3"],
  ["Command & conduct", "KFD members must comply with laws and ordinances of:", "The United States, Tennessee, and the City of Knoxville", "The City of Knoxville only", "Tennessee only", "Only the jurisdiction where the station is located", "The conduct rule requires compliance with federal, state, and City laws and ordinances.", "Article 3 §3.2.6, p. 3"],
  ["Command & conduct", "When addressing an officer or person of higher authority, a member should use:", "The person's proper title", "Only the person's last name", "The person's station assignment", "Any informal form the member prefers", "Members must show respect for rank and use the proper title when addressing or referring to higher authority.", "Article 3 §3.2.7, p. 3"],
  ["Command & conduct", "How should members communicate with the public and fellow City employees?", "Courteously, avoiding harsh, violent, profane, or insulting language", "Informally unless a complaint is made", "Only through a Company Officer", "In writing whenever possible", "Article 3 requires courteous relationships and prohibits harsh, violent, profane, or insulting language.", "Article 3 §3.2.9, p. 4"],
  ["Command & conduct", "When a recognized City official or KFD Chief Officer enters a station, members should:", "Rise and address the visitor courteously by title and name", "Remain seated unless directly addressed", "Report immediately to the apparatus floor", "Call Dispatch for confirmation", "Officers and firefighters are directed to rise upon recognition and speak courteously and respectfully.", "Article 3 §3.2.11, p. 4"],
  ["Command & conduct", "Which action violates KFD's truthfulness rule?", "Willingly misrepresenting or falsifying a matter verbally or in writing", "Correcting an earlier report", "Requesting clarification", "Declining to speculate about unknown facts", "Members may not willingly misrepresent or falsify any matter, whether spoken or written.", "Article 3 §3.2.13, p. 4"],
  ["Command & conduct", "May a member appropriate Department property or contract supplies for personal use?", "No", "Yes, if the item is scheduled for replacement", "Yes, with coworker approval", "Only while off duty", "Members may not sell, give away, or appropriate Department property, contract supplies, or metered services.", "Article 3 §3.2.16, p. 4"],
  ["Command & conduct", "KFD members are prohibited from gambling:", "While on duty, in uniform, or on City property", "Only inside a fire station", "Only when money changes hands", "Only during normal business hours", "The gambling prohibition applies while on duty, in uniform, or on City property.", "Article 3 §3.2.17, p. 4"],
  ["Command & conduct", "Unless official duties require it, firearms or ammunition may be stored in a City-owned vehicle assigned to an employee:", "Never", "Only in a locked compartment", "Only with a carry permit", "Only when the vehicle is off City property", "Employees may not store firearms or ammunition in assigned City-owned vehicles unless official duties specifically require it.", "Article 3 §3.2.18(c), p. 5"],
  ["Command & conduct", "May a hazardous or unsafe item be kept in a member's locker without authorization?", "No", "Yes, if labeled", "Yes, for one shift", "Only with another member present", "Hazardous or unsafe items may not be kept in lockers or on City property without proper authorization.", "Article 3 §3.2.19, p. 5"],
  ["Command & conduct", "May long-distance calls be made on fire-station telephones?", "No", "Yes, with Company Officer approval", "Yes, during sleeping hours", "Only for calls inside Tennessee", "Article 3 prohibits long-distance calls on fire-station telephones.", "Article 3 §3.2.21, p. 5"],
  ["Command & conduct", "A gift appears intended to influence a member's official actions. The member must:", "Refuse it", "Accept it and report it after the shift", "Share it with the company", "Accept it if its value is under $25", "Members may not accept gifts, favors, or services intended or reasonably expected to influence official duty or reward an official act.", "Article 3 §3.2.24, p. 6"],
  ["Command & conduct", "While on duty or in uniform, a member may solicit subscriptions or sell tickets only with permission from:", "The Fire Chief", "The Company Officer", "The station's senior member", "The charitable organization", "Solicitation or ticket sales while on duty or in uniform require the Chief's permission.", "Article 3 §3.2.25, p. 6"],
  ["Command & conduct", "Which substance rule applies while a member is on duty?", "Alcohol may not be consumed or possessed, and illegal drugs may not be possessed or used", "Alcohol is allowed with a meal", "Only possession of illegal drugs is prohibited", "Prescription drugs never need disclosure", "Members may not possess or use illegal drugs and may not consume or possess alcohol while on duty.", "Article 3 §3.2.27, p. 6"],
  ["Command & conduct", "A member communicates publicly as a representative of KFD about Department actions or policies. What is required first?", "Fire Chief approval", "A disclaimer only", "Company Officer approval only", "No approval for oral comments", "Solicited or unsolicited communications as a KFD representative require prior approval from the Fire Chief.", "Article 3 §3.2.35, p. 7"],
  ["Command & conduct", "Failure to uphold Department and City rules may result in discipline up to and including:", "Termination", "Transfer only", "Loss of trade time only", "A counseling form only", "Members who fail to uphold standards, policies, procedures, rules, and regulations may face discipline including termination.", "Article 3 §3.3.1, p. 9"],
  ["Command & conduct", "A felony or misdemeanor conviction may lead to:", "Disciplinary action", "Automatic promotion ineligibility only", "No Department action", "A mandatory transfer only", "Article 3 permits disciplinary action when a member has been convicted of a felony or misdemeanor.", "Article 3 §3.3.2, p. 9"],
  ["Response readiness", "When selecting a route for an emergency or non-emergency response, apparatus should generally:", "Take the shortest route and avoid railroad crossings when possible", "Always use the designated commercial route", "Avoid highways in every case", "Use the route with the most traffic signals", "Apparatus should use the shortest route and avoid railroad crossings when possible.", "Article 3 §3.4.5, p. 10"],
  ["Response readiness", "Who must ensure all assigned personnel are seated with seatbelts fastened before apparatus moves?", "The Company Officer", "The driver alone", "Dispatch", "Each member without officer oversight", "The Company Officer must verify assigned personnel are in position and belted before movement.", "Article 3 §3.4.8, p. 11"],
  ["Response readiness", "Emergency-vehicle privileges relieve the driver of the duty to operate with due regard for safety:", "Never", "Whenever the siren is operating", "Only at red lights", "Only during a confirmed structure fire", "The cited law preserves the driver's duty of due regard and does not protect reckless disregard for safety.", "Article 3 §3.4.10, p. 12"],
  ["Response readiness", "Officers and drivers should position apparatus so it does not:", "Obstruct hydrants or hinder other apparatus and equipment", "Face away from the station", "Use more than one traffic lane", "Remain within sight of Command", "Apparatus should not obstruct hydrants or prevent the movement of other apparatus or equipment.", "Article 3 §3.4.11, p. 12"],
  ["Response readiness", "When possible, hose lines should be laid so they do not:", "Block avenues of travel", "Cross a sidewalk", "Pass near the command post", "Extend beyond the first-due area", "Officers and drivers should avoid laying hose in a manner that blocks travel routes.", "Article 3 §3.4.12, p. 12"],
  ["Response readiness", "Written set-ups and preplanned assignments should be followed:", "Unless circumstances require different action", "Only on first alarms", "Only after a District Chief arrives", "Without exception", "Members should follow written set-ups and preplans unless incident circumstances require another action.", "Article 3 §3.4.14, p. 13"],
  ["Response readiness", "Second-alarm or greater companies traveling to an incident should:", "Use extreme caution and monitor radio traffic for orders", "Silence all radios until arrival", "Follow the first-arriving apparatus closely", "Stage automatically one block away", "Later-alarm companies must use extreme caution, watch for other responding units, and monitor transmissions.", "Article 3 §3.4.15, p. 13"],
  ["Response readiness", "What does Article 3 say about freelancing at incidents?", "It is unacceptable", "It is allowed for Senior Firefighters", "It is allowed when radio traffic is heavy", "It is encouraged during rescue operations", "Members should stay with their company unless assigned elsewhere; freelancing is unacceptable.", "Article 3 §3.4.21, p. 13"],
  ["Response readiness", "After use, Department apparatus and emergency equipment should be returned to full service:", "As soon as possible", "By the next shift", "After the monthly inventory", "Only when Logistics directs it", "All members must assist in restoring units to full in-service status as soon as possible.", "Article 3 §3.4.22, p. 13"],
  ["Response readiness", "Members are expected to know street names and locations:", "In their assigned response area and generally throughout the city", "Only within one mile of their station", "Only on the official preplan list", "Only in their first-due fire territory", "Members must learn their assigned response area and develop general citywide street knowledge.", "Article 3 §3.4.24, p. 14"],
  ["Response readiness", "Who must use seatbelts in Fire Department vehicles?", "All Fire Department personnel", "Only front-seat occupants", "Only the driver and officer", "Only personnel responding emergently", "Seatbelts must be provided and used by all KFD personnel in all vehicles.", "Article 3 §3.4.26, p. 14"],
  ["Response readiness", "A KFD unit is dispatched near the corporate limits and jurisdiction is uncertain. What should the Officer-in-Charge do first?", "Begin lifesaving and suppression efforts immediately", "Wait until ownership records are checked", "Stage until another agency arrives", "Return to the city limits", "KFD begins lifesaving and suppression and continues until jurisdiction is jointly determined and command can be transferred.", "Article 3 §3.4.28, p. 14"],
  ["Work rules", "A company is still operating at a fire during shift change. Who arranges transportation after the oncoming members reach the station?", "The Fire Officer contacts the on-duty District Chief", "Dispatch automatically sends a unit", "The outgoing driver", "The Administrative Office", "The Fire Officer calls the on-duty District Chief to arrange transportation for the relief crew.", "Article 3 §3.5.4, p. 16"],
  ["Work rules", "A member is still engaged at an emergency at 7:00 a.m. The member remains until:", "Relieved by the Incident Commander", "The oncoming shift reaches the station", "7:30 a.m.", "The Company Officer leaves", "Members at an emergency at shift change remain until the IC relieves them.", "Article 3 §3.5.5, p. 16"],
  ["Work rules", "Requests for Firefighting Division leave must be approved by immediate supervisors, including the District Chief, and submitted:", "On the pre-watch", "After the shift begins", "Directly to Payroll", "At least 30 days in advance", "Leave requests are approved through immediate supervisors and the District Chief and submitted on the pre-watch.", "Article 3 §3.5.8, p. 17"],
  ["Work rules", "A single 24-hour annual-leave day may be taken on a holiday when:", "Prior approval is obtained and holiday staffing is confirmed", "The request is made the same morning", "Another member volunteers to float", "The member has no sick leave", "Holiday annual leave requires prior approval and is not approved until staffing is confirmed.", "Article 3 §3.5.10, p. 18"],
  ["Work rules", "Can KFD cancel previously approved annual leave?", "Yes, for emergencies or operational conditions", "No, once it appears on the pre-watch", "Only with the member's consent", "Only on holidays", "The Department reserves the right to cancel annual leave when emergencies or operations require it.", "Article 3 §3.5.12, p. 18"],
  ["Work rules", "Emergency use of annual leave requires approval from:", "The District Chief", "The Company driver", "Payroll", "Dispatch", "A District Chief may approve emergency annual leave and may require verification.", "Article 3 §3.5.13, p. 18"],
  ["Work rules", "A Leave of Absence request must be made through:", "The member's supervisor", "A coworker", "The union only", "The Training Academy", "Members request a Leave of Absence through their supervisor before approval or authorization.", "Article 3 §3.5.16, p. 19"],
  ["Work rules", "Who may request medical evidence for a shorter period of sick leave when appropriate?", "The Chief, Deputy Chief, or Assistant Chief", "Any firefighter", "Dispatch", "Only Risk Management", "The Chief, a Deputy Chief, or an Assistant Chief may request a medical statement for shorter sick-leave periods.", "Article 3 §3.5.20, p. 19"],
  ["Work rules", "After an injury, a medical release may be required before return to regular duty by:", "The Fire Chief", "The apparatus driver", "The member's physician alone", "The watch-duty member", "The Chief may require a medical statement of release before regular duty resumes.", "Article 3 §3.5.21, p. 19"],
  ["Work rules", "A member becomes ill during paid annual leave. What may the member request?", "Temporarily end vacation and charge the time to sick leave", "Convert the entire year of leave to overtime", "Extend annual leave automatically", "Use trade time without approval", "A member may request that vacation be temporarily terminated and the time charged to sick leave.", "Article 3 §3.5.24, p. 20"],
  ["Work rules", "While off duty because of a job-related injury, a member continues to accrue:", "Sick and annual leave", "Annual leave only", "Sick leave only", "Neither type of leave", "Members off for job-related injury continue accruing both sick and annual leave.", "Article 3 §3.5.25, p. 20"],
  ["Work rules", "An on-duty injury must be reported to whom for direction to treatment?", "The Health & Safety Officer or designee", "The news media officer", "The station cook", "The Civil Service Board", "All duty injuries go to the Health & Safety Officer or designee, who directs treatment and reports to Risk Management.", "Article 3 §3.5.27, p. 20"],
  ["Work rules", "If job-injury treatment was not authorized in advance, which physicians will normally be paid by the City?", "Physicians authorized by the City", "Any physician selected by the member", "Only emergency-room physicians", "Only the member's family physician", "Without advance authorization, the City pays only physicians it has authorized.", "Article 3 §3.5.28, p. 20"],
  ["Work rules", "If working conditions prevent voting outside work hours, a member may receive:", "Sufficient coordinated time off to vote", "A full 24-hour shift off automatically", "Overtime pay instead of voting time", "No accommodation", "Members may receive enough time off to vote when coordinated with the supervisor and other voting options are unavailable.", "Article 3 §3.5.33, p. 21"],
  ["Work rules", "May one member pay another to work all or part of a shift?", "No", "Yes, if both sign the trade form", "Yes, below a set hourly rate", "Only with District Chief approval", "Article 3 expressly prohibits paying another member to work a shift or any portion of it.", "Article 3 §3.5.34(e), p. 21"],
  ["Work rules", "KFD members may engage in a strike:", "Never", "Only after a union vote", "Only while off duty", "Only when annual leave is denied", "Strikes, including concerted failure to report, work stoppage, slowdown, or partial abstention from duty, are prohibited.", "Article 3 §3.5.36, p. 22"],
  ["Work rules", "Who has the right to transfer and assign members within KFD based on classification or operational need?", "The Fire Chief and designees", "Any Senior Firefighter", "Dispatch", "The station committee", "The Chief and designees may transfer and assign members within the Department.", "Article 3 §3.6.1, p. 24"],
  ["Work rules", "Who is responsible for proper operation of life-saving equipment?", "Each member", "Only the Company Officer", "Only Logistics", "The previous shift", "Article 3 makes each member responsible for proper operation of life-saving equipment.", "Article 3 §3.6.2, p. 24"],
  ["Work rules", "A member finds an article at an alarm. May the member keep it?", "No", "Yes, if no owner is immediately identified", "Yes, after notifying a coworker", "Only if it has no monetary value", "Members may not retain or misappropriate articles found at alarms or other assignments.", "Article 3 §3.6.4, p. 25"],
  ["Work rules", "Beds may normally be occupied after noon only when:", "Training, inspections, and similar details are complete", "The Company Officer is asleep", "No calls occurred that morning", "The station has completed lunch", "After noon, bed use is allowed only after training, inspections, and similar details are finished.", "Article 3 §3.6.7, p. 25"],
  ["Work rules", "Who decides whether sleeping is permitted when an activity continues during sleeping hours?", "The Company Officer", "The member on watch", "The station's most senior firefighter", "Dispatch", "The Company Officer determines whether sleeping is permitted when a function or activity is in progress.", "Article 3 §3.6.10, p. 25"],
  ["Work rules", "What is the minimum approved sleepwear in a station?", "A Fire Department T-shirt with gym shorts or sweats", "Any civilian clothing", "Class A trousers and shirt", "Turnout gear", "Minimum sleepwear is a Department T-shirt and sportswear gym shorts or sweats.", "Article 3 §3.6.11, p. 25"],
  ["Work rules", "A privately owned vehicle may be parked inside a fire station only with special permission from:", "The Deputy Chief of Operations", "The Company Officer", "The Fire Marshal", "The Logistics Officer", "Private vehicles require special permission from the Deputy Chief of Operations and may never block apparatus positions.", "Article 3 §3.6.16, p. 26"],
  ["Work rules", "Appointments for group station tours are arranged through:", "The Administrative Office", "Dispatch", "The Training Center", "Any on-duty firefighter", "Group tours must be arranged through Administration and logged by the Company Officer or designee.", "Article 3 §3.6.17, p. 26"],
  ["Work rules", "When raising or lowering the American flag, members performing the duty must wear:", "The complete uniform of the day", "Class A uniform only", "Workout clothing", "Turnout gear", "The flag is handled with dignity by members in the complete uniform of the day.", "Article 3 §3.6.21, p. 26"],
  ["Work rules", "May a member refuse to respond promptly to a duty station or assignment?", "No", "Yes, if the assignment is outside first due", "Yes, after midnight", "Only when not riding an apparatus", "Because of KFD's emergency mission, members may not refuse prompt response to an assignment.", "Article 3 §3.6.23, p. 27"],
  ["Work rules", "Floating assignments for firefighters should be distributed:", "Fairly and equally within the applicable rank", "Only to the newest member", "Only to Senior Firefighters", "At the Company Officer's sole discretion without records", "Floating is used for staffing and is shared equally; records are maintained to ensure fairness.", "Article 3 §3.6.27, p. 27"],
  ["Work rules", "Who may deviate from normal floating guidelines when special certification or rank is needed?", "The Shift Commander", "Any member asked to float", "Dispatch", "The Administrative Office clerk", "The Shift Commander may deviate from floating guidelines when special circumstances require rank or certification.", "Article 3 §3.6.29, p. 27"],
  ["Work rules", "A member is required to float after reporting to the primary station. Who is responsible for arranging prompt transportation?", "The member", "Dispatch", "The receiving Company Officer", "The Administrative Office", "The member must obtain necessary transportation; personal-auto use may qualify for predetermined float pay.", "Article 3 §3.6.33, p. 28"],
  ["Work rules", "After a transfer, personal belongings should normally be removed from the former locker within:", "Three shifts", "One shift", "Seven calendar days", "Thirty days", "Transferred members normally have three shifts to remove belongings unless circumstances prevent it.", "Article 3 §3.6.37, p. 30"],
  ["Work rules", "Personal property other than locker clothing and grooming items may remain at a station beyond the member's scheduled shift only with permission from:", "The District Chief", "Any coworker", "The apparatus driver", "Dispatch", "Longer storage of personal property requires District Chief permission, apart from normal locker items.", "Article 3 §3.6.40, p. 30"],
  ["Work rules", "Who is responsible for a valid moving violation or red-light-camera fine involving a City vehicle?", "The vehicle operator", "The City automatically", "The Company Officer", "The entire company", "Proven valid fines or moving citations are the responsibility of the operator.", "Article 3 §3.6.42, p. 30"],
  ["Work rules", "Required certifications and EMS licenses must generally be maintained:", "For as long as required by employment, agreement, or position", "Only through probation", "Until the first promotion", "Only when the Department pays renewal fees", "Members are responsible for maintaining required licenses and certifications unless the Chief gives express written permission otherwise.", "Article 3 §3.6.43, pp. 30-31"],
  ["Command & conduct", "Which computer use takes priority over personal use?", "Run reports and pertinent Department business", "Online training selected by the member", "Personal email", "Entertainment during standby", "Run reports and relevant KFD business always take precedence over other computer use.", "Article 3 §3.7.1, p. 32"],
  ["Command & conduct", "May a member use another member's password or access their files without authorization?", "No", "Yes, on the same shift", "Yes, for a run report", "Only after 1700", "Using another member's password or accessing files without authorization is prohibited.", "Article 3 §3.7.2, p. 32"],
  ["Command & conduct", "KFD email may be used to conduct a personal business venture:", "Never", "Only off duty", "Only with a disclaimer", "Only from a station computer", "The email system may not be used to solicit or conduct personal business ventures.", "Article 3 §3.7.3, p. 32"],
  ["Command & conduct", "Who should be contacted to move Department computer equipment?", "Information Systems", "Any on-duty company", "Logistics without notice", "The member using the computer", "Information Systems is responsible for moving computer equipment.", "Article 3 §3.7.7, p. 32"],
  ["Work rules", "Who assigns and rotates station watch-duty times?", "The Company Officer", "Dispatch", "The outgoing watch member", "The Administrative Office", "The Company Officer notifies members of assigned watch times and rotates the assignments.", "Article 3 §3.8.2, p. 33"],
  ["Work rules", "The station watch activity diary is retained in FireHouse as:", "A legal, permanent record", "A temporary note deleted monthly", "An informal shift reminder", "A payroll document", "Watch activities are entered in FireHouse and protected as a legal, permanent record.", "Article 3 §3.8.4(b), p. 33"],
  ["Work rules", "If the normal alarm-notification system is inoperable, who must properly notify station members of an alarm?", "The member on watch duty", "The cook", "The apparatus driver", "The previous shift", "Alarm notification is a primary watch responsibility, including when standard systems fail.", "Article 3 §3.8.4(d), p. 33"],
  ["Work rules", "If information about an alarm is questionable, the watch-duty member should:", "Call E-911 Dispatch for verification before response", "Cancel the response", "Wait for a second alarm", "Ask a visitor", "Questions about an alarm are verified with E-911 Dispatch before response.", "Article 3 §3.8.4(e), p. 33"],
  ["Work rules", "While on watch, a member must remain:", "Within hearing distance of alarm-receiving devices and station phones", "On the apparatus floor at all times", "At the front entrance", "Inside the watch room without exception", "Watch personnel must remain within hearing distance of alarm devices, the fire phone, and station phones.", "Article 3 §3.8.6, p. 34"],
  ["Work rules", "A defect in radio equipment at the watch desk must be reported immediately to:", "The highest-ranking station officer and Dispatch", "Logistics at the end of the month", "The next watch member only", "The Training Center", "Watch personnel maintain radio security and report defects to the ranking officer and Dispatch Center.", "Article 3 §3.8.8, p. 34"],
  ["Work rules", "The member being relieved from watch duty must:", "Pass all necessary information to the relief member", "Leave immediately when the relief arrives", "Email Administration only", "Clear the activity diary", "A complete watch handoff includes all necessary information.", "Article 3 §3.8.9, p. 34"],
  ["Work rules", "Fire phones may be used for:", "Official Department business only", "Any local call", "Personal calls after 1700", "Long-distance calls with officer approval", "The member on watch may not permit fire phones to be used for non-Department business.", "Article 3 §3.8.11, p. 34"],
  ["Work rules", "During a station power failure, the watch-duty member must immediately notify ranking officers and ensure operation of:", "Overhead doors and their safety sensors", "The kitchen appliances", "Personal phone chargers", "The station television", "Power-failure duties include notifying officers and ensuring overhead doors and safety sensors can operate.", "Article 3 §3.8.12, p. 34"],
  ["Work rules", "A watch-duty member becomes too ill to continue. Who must be notified?", "The highest-ranking officer working at the station", "Dispatch only", "The next scheduled watch member only", "The Administrative Office the next day", "Illness or another condition preventing continued watch must be reported to the ranking station officer.", "Article 3 §3.8.14, p. 35"],
  ["Work rules", "Violations of rules or orders in or around quarters should be reported by watch personnel to:", "The highest-ranking officer working at the station", "The public information officer", "A family member", "The next shift", "Watch-duty members report violations in or about quarters to the ranking officer.", "Article 3 §3.8.15, p. 35"],
  ["Work rules", "When station alerting devices are out of service, sleeping watch is:", "Suspended", "Extended to 8:00 a.m.", "Unchanged", "Assigned only to officers", "Sleeping watch is suspended until alerting devices are restored.", "Article 3 §3.8.18, p. 35"],
  ["Work rules", "Members other than the watch-duty member should answer a ringing station phone:", "Promptly if the watch member is temporarily away", "Never", "Only after five rings", "Only during business hours", "All members share responsibility for prompt phone answering when watch personnel are temporarily absent.", "Article 3 §3.8.19, p. 35"],
  ["EMS & HazMat", "At a HazMat incident, who must be designated to monitor operations?", "A Safety Officer", "A Public Information Officer", "A Transportation Officer", "A Supply Officer", "The HazMat command guideline requires designation of a Safety Officer to monitor operations.", "Article 4 §4.3.1, PDF p. 30"],
  ["EMS & HazMat", "Before committing KFD personnel at a HazMat incident, the initial size-up should consider:", "Wind, humidity, topography, area involved, rescue need, and material type and hazards", "Only wind direction and product name", "Only the number of exposed patients", "Property value and media presence", "The guideline lists environmental conditions, incident geography, rescue need, and the material's type and hazards as pre-commitment factors.", "Article 4 §4.3.1, PDF p. 30"],
  ["EMS & HazMat", "What is the first initial objective listed for a HazMat response?", "Isolate and deny entry", "Begin offensive product control", "Move Command into the Hot Zone", "Send an unprotected member to identify the product", "The HazMat guideline begins initial objectives with isolating the area and denying entry.", "Article 4 §4.3.1, PDF p. 30"],
  ["EMS & HazMat", "Which sources can help identify a hazardous material during size-up?", "Labels, placards, markers, and shipping papers", "Building tax records only", "Witness social-media posts", "Apparatus maintenance records", "The hazard-identification list includes labels, placards, markers, and shipping papers.", "Article 4 §4.3.1, PDF p. 30"],
  ["Rescue & safety", "If an incident escalates into a violent or potentially violent situation, personnel should retreat, request KPD, and:", "Activate the portable-radio emergency button or verbalize code blue", "Remain in place without radio traffic", "Move apparatus closer to the threat", "Request a second fire alarm before retreating", "The violent-situation guideline directs personnel to a safe area, an emergency KPD response, and activation of the emergency button or a radio code-blue message.", "Article 4 §4.5.6, PDF p. 70"],
];

const seededQuestions: SourceQuestion[] = additionalSeeds.map(([topic, prompt, correct, wrongA, wrongB, wrongC, explanation, source], index) => {
  const id = 31 + index;
  const answer = id % 4;
  const options = [wrongA, wrongB, wrongC];
  options.splice(answer, 0, correct);
  return { id, topic, prompt, options, answer, explanation, source };
});

export const canonicalQuestions: Question[] = [...baseQuestions, ...seededQuestions].map((question) => ({
  ...question,
  ruleId: question.id,
}));

const applicationLead: Record<Topic, string> = {
  "Command & conduct": "Apply the KFD command-and-conduct rule to this situation:",
  "Response readiness": "During an operational-readiness check, the crew must apply the cited rule:",
  "Work rules": "A supervisor is checking whether this shift decision follows KFD policy:",
  "Fire operations": "At an incident, the officer must choose the action that matches the operating guideline:",
  "EMS & HazMat": "In an EMS or hazardous-materials scenario, apply the cited guideline:",
  "Rescue & safety": "During a rescue or safety size-up, choose the rule-compliant response:",
};

const applicationQuestions: Question[] = canonicalQuestions.map((question) => ({
  ...question,
  id: 1000 + question.id,
  prompt: `${applicationLead[question.topic]} ${question.prompt}`,
}));

// The expanded pool provides two testing forms per verified rule. Quiz selection
// limits each exam to one form of a rule, so alternate wording never creates a
// duplicate knowledge point inside the same set.
export const questions: Question[] = [...canonicalQuestions, ...applicationQuestions];

export type Flashcard = readonly [string, string, string];

export const flashcards: Flashcard[] = canonicalQuestions.flatMap((question) => [
  [question.prompt, question.options[question.answer], question.source] as Flashcard,
  [`Explain the rule behind: ${question.options[question.answer]}`, question.explanation, question.source] as Flashcard,
]);

export const sourceCoverage = [
  { title: "Article 3", detail: "General Rules & Regulations", status: "Question-ready", tone: "ready" },
  { title: "Article 4", detail: "General Operating Guidelines", status: "Question-ready", tone: "ready" },
  { title: "Essentials of Fire Fighting", detail: "IFSTA, 6th edition", status: "Study from official book", tone: "pending" },
  { title: "Pumping Apparatus", detail: "Driver/Operator, 3rd edition", status: "Study from official book", tone: "pending" },
  { title: "Company Officer", detail: "IFSTA, 5th ed., Chapters 1 & 3", status: "Study from official book", tone: "pending" },
] as const;
