export type Topic =
  | "Command & conduct"
  | "Response readiness"
  | "Work rules"
  | "Fire operations"
  | "EMS & HazMat"
  | "Rescue & safety";

export type Question = {
  id: number;
  topic: Topic;
  prompt: string;
  options: string[];
  answer: number;
  explanation: string;
  source: string;
};

export const questions: Question[] = [
  {
    id: 1,
    topic: "Command & conduct",
    prompt: "A member wants an interview with someone above their supervisor. What is the normal first step?",
    options: [
      "Contact the Administrative Office directly",
      "Ask the supervisor and briefly state the reason",
      "Send a written request to the Fire Chief",
      "Ask any Chief Officer encountered on duty",
    ],
    answer: 1,
    explanation: "The request normally goes through the member's supervisor, with a brief reason. Certain issues such as harassment or safety are not restricted by this route.",
    source: "Article 3 §3.1.2, p. 1",
  },
  {
    id: 2,
    topic: "Command & conduct",
    prompt: "A superior officer gives an order that conflicts with a previous order. What should the member do?",
    options: [
      "Follow the newest order without comment",
      "Follow the order from the higher-ranking officer",
      "Inform the officer who issued the conflicting order and follow that officer's instructions",
      "Stop work until both officers meet",
    ],
    answer: 2,
    explanation: "The member informs the officer who issued the conflicting order and is then governed by that officer's instructions.",
    source: "Article 3 §3.1.6, p. 2",
  },
  {
    id: 3,
    topic: "Command & conduct",
    prompt: "If a member doubts the legality of an order, the member should:",
    options: [
      "Refuse it immediately",
      "Ask the issuing supervisor to clarify it in writing or confer with higher authority",
      "Complete it and file a grievance afterward",
      "Ask another firefighter for an interpretation",
    ],
    answer: 1,
    explanation: "Members must not obey an order they know or should know requires an illegal act. When in doubt, they should request written clarification or confer with higher authority.",
    source: "Article 3 §3.1.7, p. 2",
  },
  {
    id: 4,
    topic: "Command & conduct",
    prompt: "A member charged with a crime other than a minor traffic offense must report it to the Administrative Office within:",
    options: ["24 hours", "48 hours", "72 hours", "Five business days"],
    answer: 2,
    explanation: "The charge must be reported as soon as possible, not to exceed 72 hours from when the member becomes aware of it.",
    source: "Article 3 §3.2.38(a), p. 8",
  },
  {
    id: 5,
    topic: "Command & conduct",
    prompt: "A current member must notify the Administrative Office of the outcome of a criminal case within:",
    options: ["12 hours", "24 hours", "72 hours", "Seven days"],
    answer: 1,
    explanation: "The outcome must be reported within 24 hours.",
    source: "Article 3 §3.2.38(b), p. 8",
  },
  {
    id: 6,
    topic: "Response readiness",
    prompt: "What is the minimum driver-license requirement while operating Fire Department apparatus?",
    options: [
      "Class C with no endorsement",
      "Commercial Class B only",
      "Valid Class D with an F endorsement, or equivalent",
      "Any valid Tennessee license",
    ],
    answer: 2,
    explanation: "Drivers must possess at least a valid Class D operator's license with an F endorsement, or equivalent, and report any status change.",
    source: "Article 3 §3.4.2, p. 9",
  },
  {
    id: 7,
    topic: "Response readiness",
    prompt: "At minimum, what PPE must firefighting personnel wear while responding to structural fires and fire alarms?",
    options: [
      "Helmet and gloves",
      "Turnout coat and turnout pants",
      "Full PPE including SCBA facepiece",
      "Station uniform and safety vest",
    ],
    answer: 1,
    explanation: "The minimum is turnout coat and turnout pants. Helmets are not to be worn while traveling, and seatbelts may not be unbuckled to don PPE.",
    source: "Article 3 §3.4.4, p. 9",
  },
  {
    id: 8,
    topic: "Response readiness",
    prompt: "If a radio goes out of service during an emergency, which statement is correct?",
    options: [
      "Notify Dispatch after the incident",
      "Notify the Incident Commander; every interior crew member must have a working portable radio",
      "Only the Company Officer needs a working portable radio",
      "The affected member may remain interior if paired with another member",
    ],
    answer: 1,
    explanation: "The IC must be notified, and each member of an interior crew must have a working portable radio.",
    source: "Article 3 §3.4.17, p. 11",
  },
  {
    id: 9,
    topic: "Response readiness",
    prompt: "An officer calling for a second alarm or greater must tell Dispatch:",
    options: ["The estimated property value", "The extent of the fire", "The nearest hydrant color", "The number of off-duty personnel needed"],
    answer: 1,
    explanation: "The officer calling for a second alarm or greater must inform Dispatch of the extent of the fire.",
    source: "Article 3 §3.4.16, p. 11",
  },
  {
    id: 10,
    topic: "Response readiness",
    prompt: "When is hearing protection required?",
    options: [
      "Only during emergency response",
      "Only when the apparatus siren is operating",
      "At all times when riding in fire apparatus or operating power equipment",
      "Only for personnel seated in the rear of apparatus",
    ],
    answer: 2,
    explanation: "Hearing protection is required at all times while riding in fire apparatus or operating power equipment.",
    source: "Article 3 §3.4.27, p. 14",
  },
  {
    id: 11,
    topic: "Work rules",
    prompt: "The Firefighting Division's schedule averages how many hours per week over a 28-day period?",
    options: ["40", "48", "56", "72"],
    answer: 2,
    explanation: "Three shifts each average 56 hours per week over a 28-day period, using 24-hour duty periods.",
    source: "Article 3 §3.5.1, p. 15",
  },
  {
    id: 12,
    topic: "Work rules",
    prompt: "A Firefighting Division member taking sick leave must notify the District Chief and Company Officer during which window?",
    options: ["5:30-6:00 a.m.", "6:00-6:15 a.m.", "6:30-6:45 a.m.", "Before 7:00 a.m."],
    answer: 1,
    explanation: "Notification is required between 6:00 and 6:15 a.m. on the morning before the shift begins.",
    source: "Article 3 §3.5.18, p. 18",
  },
  {
    id: 13,
    topic: "Work rules",
    prompt: "Trade time must normally be approved by the District Chief and Fire Officer at least:",
    options: ["12 hours before", "24 hours before", "48 hours before", "One week before"],
    answer: 1,
    explanation: "Trade time requires approval at least 24 hours before it occurs.",
    source: "Article 3 §3.5.34(a), p. 20",
  },
  {
    id: 14,
    topic: "Work rules",
    prompt: "During a 24-hour shift, firefighting apparatus may normally be used to obtain groceries or pick up restaurant food how many times?",
    options: ["Once", "Twice", "Three times", "As often as needed within first due"],
    answer: 1,
    explanation: "The limit is two times per 24-hour shift; crews must remain in their first-due EMS territory and may not sit down to eat at the restaurant.",
    source: "Article 3 §3.6.35, p. 27",
  },
  {
    id: 15,
    topic: "Work rules",
    prompt: "Which statement about sleeping watch is correct?",
    options: [
      "It is permitted from 10:00 p.m. to 6:00 a.m.",
      "It transfers alarm responsibilities to Dispatch",
      "It is permitted from 11:00 p.m. to 7:00 a.m. but does not relieve watch responsibilities",
      "It is suspended only when the fire phone is out of service",
    ],
    answer: 2,
    explanation: "Sleeping watch is permitted from 11:00 p.m. to 7:00 a.m., but all alarm receipt and transmission duties remain in force.",
    source: "Article 3 §3.8.17, p. 35",
  },
  {
    id: 16,
    topic: "Fire operations",
    prompt: "Who is responsible for evaluating and continuously reevaluating risk throughout an incident?",
    options: ["The first-arriving driver", "The Incident Commander", "The Accountability Officer", "The senior firefighter on the attack line"],
    answer: 1,
    explanation: "Risk assessment is the IC's responsibility and continues for the full duration of the incident.",
    source: "Article 4 §4.1.1, p. 2",
  },
  {
    id: 17,
    topic: "Fire operations",
    prompt: "Under the residential fire attack guideline, a second alarm dispatches:",
    options: [
      "One engine and one ladder",
      "Two engines and one ladder",
      "Two engines and two ladders",
      "Three engines and one rescue company",
    ],
    answer: 1,
    explanation: "A second alarm dispatches two additional engine companies and one additional ladder company.",
    source: "Article 4 §4.1.2, p. 6",
  },
  {
    id: 18,
    topic: "Fire operations",
    prompt: "How should the first-arriving engine generally position at a structure fire?",
    options: [
      "Directly in front of the A side",
      "Past the structure, leaving the A side open for the ladder company",
      "At the nearest hydrant until assigned",
      "One block away in Level I staging",
    ],
    answer: 1,
    explanation: "The first engine positions past the structure to preserve the A side for the ladder company.",
    source: "Article 4 §4.1.2, p. 7",
  },
  {
    id: 19,
    topic: "Fire operations",
    prompt: "Until relieved by the next RIT crew, the second-arriving engine/quint should perform:",
    options: ["Ventilation", "RIT functions", "Salvage", "Accountability Officer duties"],
    answer: 1,
    explanation: "Its listed actions include establishing water supply, deploying a backup line, and performing RIT functions until relieved.",
    source: "Article 4 §4.1.2, p. 8",
  },
  {
    id: 20,
    topic: "Fire operations",
    prompt: "In RECEO VS, which pair is identified as actions of opportunity?",
    options: ["Rescue and exposures", "Confine and extinguish", "Ventilate and salvage", "Extinguish and overhaul"],
    answer: 2,
    explanation: "Rescue, exposures, confinement, extinguishment, and overhaul are sequential actions; ventilation and salvage are actions of opportunity.",
    source: "Article 4 §4.1.2, pp. 6-7",
  },
  {
    id: 21,
    topic: "Fire operations",
    prompt: "The offensive-versus-defensive guideline organizes decision-making around:",
    options: ["Life-Safety-Property", "Value-Time-Size", "Risk-Resources-Response", "Smoke-Heat-Flow"],
    answer: 1,
    explanation: "The guideline uses Value, Time, and Size. Its required fire-flow prompt is L × W ÷ 3.",
    source: "Article 4 §4.1.3, p. 10",
  },
  {
    id: 22,
    topic: "Fire operations",
    prompt: "A hydrant with a red bonnet indicates which rated flow?",
    options: ["1,500+ gpm", "1,000-1,499 gpm", "500-999 gpm", "Less than 500 gpm"],
    answer: 3,
    explanation: "Red indicates less than 500 gpm. Solid red hydrants or hydrants with a red bonnet are limited to refilling booster tanks under this guideline.",
    source: "Article 4 §4.1.12, p. 24",
  },
  {
    id: 23,
    topic: "Rescue & safety",
    prompt: "For swiftwater incidents, where does the warm zone begin?",
    options: ["At the water's edge", "5 feet from the water's edge", "15 feet from the water's edge", "25 feet from the water's edge"],
    answer: 2,
    explanation: "The warm zone begins 15 feet from the water's edge; the cold zone is anything greater than 15 feet away, and the hot zone is in the water.",
    source: "Article 4 §4.4.1, p. 55",
  },
  {
    id: 24,
    topic: "Rescue & safety",
    prompt: "At a trench collapse, the first-arriving apparatus should position at least how far from the trench?",
    options: ["50 feet", "75 feet", "100 feet", "150 feet"],
    answer: 2,
    explanation: "The first apparatus should stop at least 100 feet away; additional arriving units stage at least 150 feet away.",
    source: "Article 4 §4.4.2, p. 57",
  },
  {
    id: 25,
    topic: "Rescue & safety",
    prompt: "Initial KFD companies at a confined-space incident operate at which level?",
    options: ["Operations", "Technician", "Awareness", "Command"],
    answer: 2,
    explanation: "Initial companies function at the Awareness level and shall not enter. Entry is defined as breaking the plane of the opening.",
    source: "Article 4 §4.4.3, p. 59",
  },
  {
    id: 26,
    topic: "Rescue & safety",
    prompt: "When must each SCBA be tested and inspected?",
    options: [
      "Weekly and after a reported malfunction",
      "At the beginning of each shift and after each use",
      "At the end of each shift only",
      "Monthly by Logistics",
    ],
    answer: 1,
    explanation: "Each SCBA is inspected at the beginning of every shift, after every use, and whenever needed to restore ready condition.",
    source: "Article 4 §4.5.2, p. 64",
  },
  {
    id: 27,
    topic: "Fire operations",
    prompt: "In Level I staging, units other than the first engine, first ladder, and second engine should generally stage:",
    options: ["At the command post", "At the primary hydrant", "Approximately one block away", "At the nearest fire station"],
    answer: 2,
    explanation: "All other responding units stage uncommitted about one block away and await Command; units must not self-assign.",
    source: "Article 4 §4.5.3, p. 65",
  },
  {
    id: 28,
    topic: "Rescue & safety",
    prompt: "What is the apparatus air-horn evacuation signal?",
    options: ["One continuous blast", "Two long blasts", "Three repeated short blasts", "Five alternating short and long blasts"],
    answer: 2,
    explanation: "The evacuation signal is three repeated short air-horn blasts; a PAR should begin as soon as possible afterward.",
    source: "Article 4 §4.5.4, p. 67",
  },
  {
    id: 29,
    topic: "Rescue & safety",
    prompt: "After jumping clear of a vehicle involved with downed wires, occupants should shuffle at least how far away?",
    options: ["5 feet", "10 feet", "20 feet", "One apparatus length"],
    answer: 1,
    explanation: "Occupants should avoid simultaneous contact with vehicle and ground, then use small shuffle steps until at least 10 feet away from the vehicle or wires.",
    source: "Article 4 §4.5.5, p. 68",
  },
  {
    id: 30,
    topic: "Rescue & safety",
    prompt: "Companies responding to a potentially violent incident should initially stage:",
    options: ["Out of sight but within 100 feet", "At least one block away", "At the nearest hydrant", "Two blocks away in all cases"],
    answer: 1,
    explanation: "Companies stage at least one block away, advise Dispatch, and remain until KPD confirms the scene is secure and FD services are required.",
    source: "Article 4 §4.5.6, p. 70",
  },
];

export const flashcards = [
  ["Conflicting orders", "Inform the officer issuing the conflicting order; follow that officer's instructions.", "Article 3 §3.1.6"],
  ["Crime charged", "Report as soon as possible, no later than 72 hours after becoming aware.", "Article 3 §3.2.38(a)"],
  ["Criminal-case outcome", "Notify the Administrative Office within 24 hours.", "Article 3 §3.2.38(b)"],
  ["Apparatus license", "Minimum valid Class D with F endorsement, or equivalent.", "Article 3 §3.4.2"],
  ["Structural-fire response PPE", "At minimum, turnout coat and turnout pants; no helmet while traveling.", "Article 3 §3.4.4"],
  ["Interior radios", "Every interior crew member must have a working portable radio.", "Article 3 §3.4.17"],
  ["Hearing protection", "Always when riding in fire apparatus or operating power equipment.", "Article 3 §3.4.27"],
  ["Sick notification", "District Chief and Company Officer, 6:00-6:15 a.m.", "Article 3 §3.5.18"],
  ["Trade-time approval", "District Chief and Fire Officer, at least 24 hours in advance.", "Article 3 §3.5.34"],
  ["Food trips", "Two per 24-hour shift, within first-due EMS territory; no dine-in.", "Article 3 §3.6.35"],
  ["Sleeping watch", "11:00 p.m.-7:00 a.m.; alarm duties remain fully in effect.", "Article 3 §3.8.17"],
  ["Second alarm", "Two additional engines and one additional ladder.", "Article 4 §4.1.2"],
  ["RECEO VS opportunity actions", "Ventilation and salvage.", "Article 4 §4.1.2"],
  ["Decision model", "Value - Time - Size; fire flow prompt L × W ÷ 3.", "Article 4 §4.1.3"],
  ["Hydrant bonnet: blue", "1,500+ gpm.", "Article 4 §4.1.12"],
  ["Hydrant bonnet: red", "Less than 500 gpm; use limited to booster-tank refill.", "Article 4 §4.1.12"],
  ["Swiftwater zones", "Cold >15 ft; warm begins 15 ft from edge; hot is in water.", "Article 4 §4.4.1"],
  ["Trench positioning", "First apparatus 100 ft; additional units 150 ft.", "Article 4 §4.4.2"],
  ["Confined-space entry", "Initial companies are Awareness only; breaking the plane counts as entry.", "Article 4 §4.4.3"],
  ["Evacuation signal", "Three repeated short air-horn blasts, followed by PAR as soon as possible.", "Article 4 §4.5.4"],
] as const;

export const sourceCoverage = [
  { title: "Article 3", detail: "General Rules & Regulations", status: "Question-ready", tone: "ready" },
  { title: "Article 4", detail: "General Operating Guidelines", status: "Question-ready", tone: "ready" },
  { title: "Essentials of Fire Fighting", detail: "IFSTA, 6th edition", status: "Study from official book", tone: "pending" },
  { title: "Pumping Apparatus", detail: "Driver/Operator, 3rd edition", status: "Study from official book", tone: "pending" },
  { title: "Company Officer", detail: "IFSTA, 5th ed., Chapters 1 & 3", status: "Study from official book", tone: "pending" },
] as const;
